# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lockfile}
  s.version = "1.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ara T. Howard"]
  s.date = %q{2010-08-10}
  s.description = %q{A ruby library for creating NFS safe lockfiles and to run arbitrary commands while holding them.}
  s.email = %q{ara.t.howard@noaa.gov}
  s.executables = ["rlock", "rlock-1.4.3"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "VERSION",
     "bin/rlock",
     "bin/rlock-1.4.3",
     "doc/rlock.help",
     "gemspec.rb",
     "install.rb",
     "lib/lockfile.rb",
     "rlock",
     "samples/a.rb",
     "samples/lock",
     "samples/lock.sh",
     "samples/lockfile",
     "samples/nfsstore.rb",
     "samples/out"
  ]
  s.homepage = %q{http://codeforpeople.com/lib/ruby/lockfile}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A ruby library for creating NFS safe lockfiles}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

